# Generated by Django 4.2 on 2023-04-14 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_tag_alter_region_name'),
        ('judge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='region',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='regions.region'),
        ),
    ]
