# Generated by Django 4.2 on 2023-04-18 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_tag_alter_region_name'),
        ('judge', '0002_judge_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='judge',
            name='managed_regions',
            field=models.ManyToManyField(related_name='managers', to='regions.region'),
        ),
    ]
