# Generated by Django 4.2 on 2023-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_region_tag_alter_region_name'),
        ('judge', '0003_judge_managed_regions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='judge',
            name='managed_regions',
            field=models.ManyToManyField(blank=True, related_name='managers', to='regions.region'),
        ),
    ]
