# Generated by Django 4.2 on 2023-04-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='tag',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=125),
        ),
    ]
